### ISSUE TITLE
Issue on Windows for G2 calc

### ISSUE THREAD

**Issue by QuantumVictor** [charlieleprince/HAL-scripts#1]
```
Traceback (most recent call last):
  File "C:\Users\Helium 1\HAL\HAL\gui\main.py", line 64, in wrapper
    return f(*args, **kwds)
  File "C:\Users\Helium 1\HAL\HAL\gui\main.py", line 649, in _playScript
    func(self)
  File "C:\Users\Helium 1\.HAL\user_scripts\g2_correlations_ALT.py", line 195, in main
    df1.rename(columns={"in box": "N"})
  File "C:\Users\Helium 1\.conda\envs\halenv\lib\site-packages\pandas\util\_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\Helium 1\.conda\envs\halenv\lib\site-packages\pandas\core\frame.py", line 4948, in drop
    return super().drop(
  File "C:\Users\Helium 1\.conda\envs\halenv\lib\site-packages\pandas\core\generic.py", line 4279, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "C:\Users\Helium 1\.conda\envs\halenv\lib\site-packages\pandas\core\generic.py", line 4323, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "C:\Users\Helium 1\.conda\envs\halenv\lib\site-packages\pandas\core\indexes\base.py", line 6644, in drop
    raise KeyError(f"{list(labels[mask])} not found in axis")
KeyError: "['v_x', 'v_z'] not found in axis"
```

**Comment by quentinmarolleau** [comment]
Weird. I did not try the code on a windows machine.
I have no problem on my linux build.

Try to comment the lines 189 and 207.

**Comment by QuantumVictor** [comment]
It works, thanks a lot !

**Comment by quentinmarolleau** [comment]
It's still an unexpected behavior, and the solution is not optimal for memory usage... I will investigate that.
